//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Additional Text is provided it must not exceed {0} characters.
        /// </summary>
        public static string Error_AdditionalTextMustNotExceedCharacters {
            get {
                return ResourceManager.GetString("Error_AdditionalTextMustNotExceedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot map {0} to {1}.
        /// </summary>
        public static string Error_CannotMapEntityToDto {
            get {
                return ResourceManager.GetString("Error_CannotMapEntityToDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {} data required.
        /// </summary>
        public static string Error_CommandDataRequired {
            get {
                return ResourceManager.GetString("Error_CommandDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to {0}.
        /// </summary>
        public static string Error_ConvertNullToEntity {
            get {
                return ResourceManager.GetString("Error_ConvertNullToEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} found.
        /// </summary>
        public static string Error_EntitiesNotFound {
            get {
                return ResourceManager.GetString("Error_EntitiesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with Id: {1} not found.
        /// </summary>
        public static string Error_EntityWithIdNotFound {
            get {
                return ResourceManager.GetString("Error_EntityWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(s) with StreetcodeId: {0} not found.
        /// </summary>
        public static string Error_EntityWithStreetcodeIdNotFound {
            get {
                return ResourceManager.GetString("Error_EntityWithStreetcodeIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facts list cannot be empty.
        /// </summary>
        public static string Error_FactsListEmpty {
            get {
                return ResourceManager.GetString("Error_FactsListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create {0}.
        /// </summary>
        public static string Error_FailedToCreateEntity {
            get {
                return ResourceManager.GetString("Error_FailedToCreateEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete {0}.
        /// </summary>
        public static string Error_FailedToDeleteEntity {
            get {
                return ResourceManager.GetString("Error_FailedToDeleteEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email message.
        /// </summary>
        public static string Error_FailedToSendEmail {
            get {
                return ResourceManager.GetString("Error_FailedToSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change status of streetcode to deleted.
        /// </summary>
        public static string Error_FailedToSoftDeleteStreetcode {
            get {
                return ResourceManager.GetString("Error_FailedToSoftDeleteStreetcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update {0}.
        /// </summary>
        public static string Error_FailedToUpdateEntity {
            get {
                return ResourceManager.GetString("Error_FailedToUpdateEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found result matching null.
        /// </summary>
        public static string Error_FoundResultMatchingNull {
            get {
                return ResourceManager.GetString("Error_FoundResultMatchingNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Context Title Already Exists.
        /// </summary>
        public static string Error_HistoricalContextTitleAlreadyExists {
            get {
                return ResourceManager.GetString("Error_HistoricalContextTitleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Image format: {0}. Only {1} are allowed.
        /// </summary>
        public static string Error_InvalidImageFormat {
            get {
                return ResourceManager.GetString("Error_InvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided token is not recognized by Monobank API.
        /// </summary>
        public static string Error_InvalidMonobankTokenException {
            get {
                return ResourceManager.GetString("Error_InvalidMonobankTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is missing or invalid.
        /// </summary>
        public static string Error_MissingUserId {
            get {
                return ResourceManager.GetString("Error_MissingUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} blob with BlobName: &quot;{1}&quot; not found.
        /// </summary>
        public static string Error_MediaBlobNotFound {
            get {
                return ResourceManager.GetString("Error_MediaBlobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News with Url: {0} not found.
        /// </summary>
        public static string Error_NewsWithUrlNotFound {
            get {
                return ResourceManager.GetString("Error_NewsWithUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string Error_PropertyIsRequired {
            get {
                return ResourceManager.GetString("Error_PropertyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal or grater than 0.
        /// </summary>
        public static string Error_PropertyMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Error_PropertyMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than 0.
        /// </summary>
        public static string Error_PropertyMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Error_PropertyMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not exceed {1} characters.
        /// </summary>
        public static string Error_PropertyMustNotExceedCharacters {
            get {
                return ResourceManager.GetString("Error_PropertyMustNotExceedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a related term by word: {0}.
        /// </summary>
        public static string Error_RelatedTermNotFound {
            get {
                return ResourceManager.GetString("Error_RelatedTermNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streetcode with Index {0} not found.
        /// </summary>
        public static string Error_StreetcodeWithIndexNotFound {
            get {
                return ResourceManager.GetString("Error_StreetcodeWithIndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streetcode with TagId: {0} not found.
        /// </summary>
        public static string Error_StreetcodeWithTagIdNotFound {
            get {
                return ResourceManager.GetString("Error_StreetcodeWithTagIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streetcode with Transliteration Url: {0} not found.
        /// </summary>
        public static string Error_StreetcodeWithTransliterationUrlNotFound {
            get {
                return ResourceManager.GetString("Error_StreetcodeWithTransliterationUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag with Title: {0} not found.
        /// </summary>
        public static string Error_TagWithTitleNotFound {
            get {
                return ResourceManager.GetString("Error_TagWithTitleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to edit or delete this comment.
        /// </summary>
        public static string Error_UserNotCommentOwner {
            get {
                return ResourceManager.GetString("Error_UserNotCommentOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слово з цим визначенням уже існує.
        /// </summary>
        public static string Error_WordDefinitionExists {
            get {
                return ResourceManager.GetString("Error_WordDefinitionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a relation between Streetcodes with corresponding Ids: ObserverId: {0} &amp; TargetId: {1}.
        /// </summary>
        public static string ErrorStreetcodeRelationError {
            get {
                return ResourceManager.GetString("ErrorStreetcodeRelationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with Id: {1} deleted successfully.
        /// </summary>
        public static string Info_EntityDeleteSuccess {
            get {
                return ResourceManager.GetString("Info_EntityDeleteSuccess", resourceCulture);
            }
        }
    }
}
